### ISSUE TITLE
Uncaught ReferenceError: exports is not defined     at retina.js:12

### ISSUE THREAD

**Issue by umairali** [strues/retinajs#269] opened 2017-01-16 12:20 UTC
I am trying to add retinajs but I am facing this error

Uncaught ReferenceError: exports is not defined at retina.js:12

I am trying with js file
`<script src="/assets/plugins/retinajs/retina.js"></script>`

**Comment by umairali** [comment] 2017-01-16 12:23
I am trying with js file 

<script src="<?php echo url("/"); ?>/assets/plugins/retinajs/retina.js"></script>

**Comment by whgandalf** [comment] 2017-01-18 21:40
Same here!

Do you know what was the last versión working good ?

**Comment by lenardchristopher** [comment] 2017-01-20 03:34
Same

**Comment by migueldemoura** [comment] 2017-01-25 22:55
Temp fix: add `var exports={};` to retina.js

**Comment by anderskristo** [comment] 2017-01-26 08:37
@migueldemoura temp fix makes it work for now.

Seems like it's the same problem as this: http://stackoverflow.com/questions/33294705/gulp-babel-exports-is-not-defined

**Comment by migueldemoura** [comment] 2017-01-26 19:19
This is a duplicate of #264

**Comment by TsuNut** [comment] 2017-02-02 05:10
Same here.

**Comment by anderskristo** [comment] 2017-02-02 09:56
@TsuNut add it above: 

`Object.defineProperty(exports, "__esModule", {
  value: true
});`

on line 11

**Comment by TsuNut** [comment] 2017-02-02 15:59
@anderskristo 

Thanks! However, I included the fix on line 11 as per instructed. No change. Reverted to 2.0.0, still no change. Wonder if using Gulp and/or concatenating has something to do with my issue?

**Comment by nbelley** [comment] 2017-02-16 13:22
Beware, adding exports as a variable will make all of your other scripts think you're using node.js, if you're not, many other scripts will fail!

**Closed** 2017-06-11 18:04 UTC
